#!/bin/sh
current_dir=$PWD
PLAYLIST_DIR=/home/yusuf/.mplaylist/

mkdir -p $PLAYLIST_DIR
cd $PLAYLIST_DIR
for arg in "$@"
do
    nq -c -q ffplay -nodisp -autoexit -loglevel quiet "$arg" &
done
cd $PWD
