snippet_support = true
verbosity = 2

[semantic_scopes]
# Map textmate scopes to kakoune faces for semantic highlighting
# # the underscores are translated to dots, and indicate nesting.
# # That is, if variable_other_field is omitted, it will try the face for
# # variable_other and then variable
# #
# To see a list of available scopes in the debug buffer, run lsp-semantic-available-scopes
variable = "variable"
entity_name_function = "function"
entity_name_type = "type"
variable_other_enummember = "variable"
entity_name_namespace = "module"

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 900 # seconds = 30 minutes

[language.dart]
# start shell to find path to dart analysis server source
filetypes = ["dart"]
roots = ["pubspec.yaml", ".git"]
command = "sh"
args = ["-c", "$HOME/Belgeler/flutter/bin/cache/dart-sdk/bin/dart $HOME/Belgeler/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp"]

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"
